version: "3.3"

services:
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: mock123

  migration:
    image: migration
    build:
      context: projects/db
    depends_on:
     - database
    command:
      - -url=jdbc:postgresql://database/platform
      - -user=platform
      - -password=mock123
      - migrate
