version: "3.3"

services:
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: migration
      POSTGRES_PASSWORD: migration

  migration:
    image: migration
    build:
      context: projects/db
    depends_on:
     - database
    command:
      - -url=jdbc:postgresql://database/platform
      - -user=migration
      - -password=migration
      - migrate
