version: 2
jobs:
  test-client-web:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Client Web
          working_directory: projects/client-web
          command: yarn install
      - run:
          name: Test Client Web
          working_directory: projects/client-web
          command: yarn run lint

  test-db-migration:
    docker:
      - image: circleci/python:3.6
    environment:
      COMPOSE_FILE: ./.circleci/docker-compose.yml
      DATABASE_URI: jdbc:postgresql://localhost:5432/platform
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Setup environment
          command: docker-compose up
      - run:
          name: Test Database Migrations
          working_directory: projects/db
          command: ./run-migration.sh

workflows:
  version: 2
  test-flow:
    jobs:
      - test-client-web
      - test-db-migration
