version: 2
jobs:
  test-client-web:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Client Web
          working_directory: packages/client-web
          command: yarn install
      - run:
          name: Test Client Web
          working_directory: packages/client-web
          command: yarn run lint

  test-backend:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Rebuild Docker Containers
          command: docker-compose build migration backend
      - run:
          name: Setup environment
          command: docker-compose up -d database
      - run:
          name: Database Startup Graceperiod
          command: sleep 5
      - run:
          name: Run Database Migrations
          command: docker-compose run migration
      - run:
          name: Lint Backend
          command: docker-compose run backend yarn lint
      - run:
          name: Test Backend
          command: docker-compose run -e CI=true backend yarn test --verbose

workflows:
  version: 2
  test-flow:
    jobs:
      - test-client-web
      - test-backend
