version: 2
jobs:
  test-client-web:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Client Web
          working_directory: projects/client-web
          command: yarn install
      - run:
          name: Test Client Web
          working_directory: projects/client-web
          command: yarn run lint

  test-db-migration:
    docker:
      - image: circleci/python:3.6
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Rebuild Docker Containers
          command: docker-compose build
      - run:
          name: Setup environment
          command: docker-compose up -d database
      - run:
          name: Database Startup Graceperiod
          command: sleep 5
      - run:
          name: Test Database Migrations
          command: docker-compose run migration

  test-backend:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Rebuild Docker Containers
          command: docker-compose build
      - run:
          name: Setup environment
          command: docker-compose up -d database
      - run:
          name: Database Startup Graceperiod
          command: sleep 5
      - run:
          name: Run Database Migrations
          command: docker-compose run migration
      - run:
          name: Install Backend
          working_directory: projects/backend
          command: yarn install
      - run:
          name: Test Backend
          working_directory: projects/backend
          command: yarn test --runInBand

workflows:
  version: 2
  test-flow:
    jobs:
      - test-client-web
      - test-db-migration
      - test-backend
