version: 2
jobs:
  test-client-web:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Client Web
          working_directory: projects/client-web
          command: yarn install
      - run:
          name: Test Client Web
          working_directory: projects/client-web
          command: yarn run lint

  test-db-migration:
    docker:
      - image: circleci/ruby:2.4.1-node

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: platform
          POSTGRES_USER: migrate
          POSTGRES_PASSWORD: migrate
    environment:
      DATABASE_URI: jdbc:postgresql://[::1]:5432/platform
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Test Database Migrations
          working_directory: projects/db
          command: ./run-migration.sh

workflows:
  version: 2
  test-flow:
    jobs:
      - test-client-web
      - test-db-migration
