version: "3.3"

services:
  database:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: platform
      POSTGRES_USER: migration
      POSTGRES_PASSWORD: migration

volumes:
  postgres-data:
